### ISSUE TITLE
Update forces you to down version numpy

### ISSUE THREAD

**Issue by JeffTweedale** [jon--lee/neuralpy#4]
on python-2.7 when tensorflow 0.12.1 has requirement numpy>=1.11.0

ERROR: neuralpy 1.3.0 has requirement numpy==1.9.2, but you'll have numpy 1.16.4 which is incompatible (why "="?).

**Comment by ArtificialZeng** [comment]
I changed to numpy==1.9.2, but can't import neuralpy.
ImportError: No module named _multiarray_umath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ailab/anaconda3/envs/python27/lib/python2.7/site-packages/neuralpy/__init__.py", line 1, in <module>
    from neural2 import *
ImportError: numpy.core.multiarray failed to import
