### ISSUE TITLE
Installing neuralpy 1.3.0 on a separate environment

### ISSUE THREAD

**Issue by sagonzal** [jon--lee/neuralpy#5]
Guys, sorry to bother with this but I can't install neuralpy on a new python  environment called  "/home/sergio/python_test_tmp/tutorial-env/¨. I set up a new environment for 3.6.10 since I have to install Keras, Tensorflow and other stuff that don't like Python 3.8.

Everything works fine, even from Spyder the IDE I use, but when I try to install pip, this is the output:

> 
> pip install neuralpy
> Collecting neuralpy
>   Using cached neuralpy-1.3.0.tar.gz (9.1 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /home/sergio/python_test_tmp/tutorial-env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0o_tdae_/neuralpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0o_tdae_/neuralpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-0o_tdae_/neuralpy/pip-egg-info
>          cwd: /tmp/pip-install-0o_tdae_/neuralpy/
>     Complete output (6 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-0o_tdae_/neuralpy/setup.py", line 2
>         print find_packages(exclude=['DEPneuralpy'])
>                           ^
>     SyntaxError: invalid syntax
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> Note: you may need to restart the kernel to use updated packages.
>

please help since I have no clue in how to proceed.

regards and thanks in advance....

**Comment by shuowang13116** [comment]
I have the same issue. I've tried everything I can find online, but none worked. 


SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
